### ISSUE TITLE
New login issue

### ISSUE THREAD

**Issue by windhamwong** [niqdev/packtpub-crawler#14]
Looks like the login page has changed. My pull request added form id and thing however it is still not working. Do you have any idea?

**Comment by niqdev** [comment]
Hi, 
a couple of days ago stopped working and I already fix it adding the missing headers with this [commit](https://github.com/niqdev/packtpub-crawler/commit/9177410bf2f639c8caf7d7276de33ff313e46870).
Can you check if is the same issue?

**Comment by niqdev** [comment]
@windhamwong Do you still have the error or is working now?
Thanks

**Comment by niqdev** [comment]
@windhamwong since I've received no answer I will close the issue
