### ISSUE TITLE
content-length not in header make spyder fail

### ISSUE THREAD

**Issue by bunam** [niqdev/packtpub-crawler#15]
Sometimes there is no content-length, i didn't know python.
It could be nice if the download is done even without progress bar

`Traceback (most recent call last):
  File "script/spider.py", line 44, in main
    packpub.download_ebooks(types)
  File "/Users/Shared/bin/packtpub-crawler/script/packtpub.py", line 129, in download_ebooks
    download_file(self.__session, download['url'], directory, download['filename'], self.__headers))
  File "/Users/Shared/bin/packtpub-crawler/script/utils.py", line 63, in download_file
    total_length = int(response.headers.get('content-length'))
TypeError: int() argument must be a string or a number, not 'NoneType'`

**Comment by niqdev** [comment]
Hi, 
please update to the latest version, until now I had no errors in the last weeks.
If happen again please give me more details on the command that you are running and C&P th complete stacktrace so that I will be able to reproduce the error.
If it happen again please reopen the issue.
Thanks
