### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by niqdev** [niqdev/packtpub-crawler#18]
Create docker image based on busybox

**Comment by niqdev** [comment]
#19

**Comment by niqdev** [comment]
Thanks @kuchy

**Comment by niqdev** [comment]
@kuchy I had a thought on your implementation and I think it works only locally, while I would like that the docker config emulates what the heroku scheduler does to be useful. Here my suggestions:
* no docker-compose needed
* copy config, script and requirements.txt inside the container
* add .dockerignore with the list of all unnecessary files
* add a script with the user schedule preferences like [this](https://github.com/niqdev/packtpub-crawler/blob/master/script/scheduler.py) that does 2 things: remove the `ebook` folder every time and run the crawler commands
* add an entry in the crontab that schedule the script

**Comment by kuchy** [comment]
If you will copy config in docker file, build it and push to docker hub, everyone who pull this image will had same config in that container :), so config shout be in host system and mounted.

I'am realy not famliar with heroku, my purpuse was to run single command (by crontab) on RPI with docker installed to save book in nfs storage. But I will check scheduler and other suggestions...

**Comment by niqdev** [comment]
You are right about the config, would be a good idea or feasible to pass an environment variable like `$CONFIG_PATH` instead?
RPI stands for Raspberry Pi ? Cool :wink:

**Comment by kuchy** [comment]
Yes, RPI stands for Raspberry Pi. `$CONFIG_PATH ` is ok but, i rather mount whole `config` folder.

**Comment by niqdev** [comment]
I've updated the Dockerfile and the readme, let me know what do you think about it and if you have any improvement to add. Thanks

**Comment by niqdev** [comment]
By the way, there is no need to add cron, APScheduler does already everything for us!

**Comment by kuchy** [comment]
APScheduler is alternative but docker can run your cron as native, as I understand this is solution only for heroku enviroment. I done some experiments (https://hub.docker.com/r/kuchy/packtpub-crawler/), i will publish that in my fork today/tomorrow.

**Comment by niqdev** [comment]
Great, when you finish let me know, so I will reference your implementation in the readme as an alternative

**Comment by kuchy** [comment]
Best soulution will be create different entrypoint for ussage on heroku cron (your's command), and 2 next for: run docker cron / run single command (this i have in 80%).

**Comment by niqdev** [comment]
Umh, I think there is a bit of confusion, Dockerfile is completely independent from heroku setup, is an alternative. I simply reused the same scheduler instead of having a different implementation with cron

**Comment by kuchy** [comment]
Ouch, maybe i check.....

**Comment by niqdev** [comment]
Can I close the issue?
If you want reference your image just add in the [readme](https://github.com/niqdev/packtpub-crawler#docker) a comment like "alternative docker image and the link" with any comment if needed

**Comment by kuchy** [comment]
In my fork I have implementation (but forgot to push Dockerfile :D) that uses standard unix cron, bur Ithink that your implementation is easier to use.
image published: https://hub.docker.com/r/kuchy/packtpub-crawler/
docker-compose: https://github.com/kuchy/packtpub-crawler/blob/docker_cron/docker-compose.yml
If you like add reference...

**Comment by niqdev** [comment]
I've updated the readme!
