### ISSUE TITLE
Err: cannot find module 'express'

### ISSUE THREAD

**Issue by fariz0020** [niqdev/packtpub-crawler#2]
Excuse me, niqdev & other developers,

I have an issue like this, after, execute node dev/server.js

![capture](https://cloud.githubusercontent.com/assets/15624898/15445795/ddb86b34-1f31-11e6-8094-e5cfb58f7d1b.JPG)

this is my prod.cfg

```
[url]
url.base=https://www.packtpub.com
url.login=/packt/offers/free-learning
# params: 0=id, 1=format
url.download=/ebook_download/{0}/{1}

#time in seconds
[delay]
delay.requests=2

[credential]
credential.email=mygoogleemail
credential.password=mygooglepassword

[path]
path.ebooks=ebooks
path.extras=ebooks/extras

[drive]
drive.oauth2_scope=https://www.googleapis.com/auth/drive
drive.client_secrets=config/client_secrets.json
drive.auth_token=config/auth_token.json
drive.gmail=mygoogleemail

[notify]
notify.host=smtp.gmail.com
notify.port=587
notify.username=mygoogleemail
notify.password=mygooglepassword
notify.from=FROM@gmail.com
notify.to=mygoogleemail, mysecondgoogleemail
```

also i want to ask, where should i put my packtpub's username and password ?

thank you very much for share this crawler,
i'm sure it will be great for everyone.

**Comment by niqdev** [comment]
Hi,
I'm glad you appreciate it, but `node dev/server.js` is meant for another purpose i.e. only helping in development.

I'll make it clear for everybody, so if you want to claim and download your free eBook you should
* clone the repo (https or ssh) `git clone https://github.com/niqdev/packtpub-crawler.git`
* create a config file with your own credentials:
```
cd packtpub-crawler
cp config/prod_example.cfg config/prod.cfg
```
and at least you should change
```
[credential]
credential.email=PACKTPUB_EMAIL
credential.password=PACKTPUB_PASSWORD
```
* verify that you have installed python and all necessary libraries with `pip`
* download your pdf running the following command from the project root directory
```
python script/spider.py -c config/prod.cfg
```

I hope this help you!

**Comment by fariz0020** [comment]
thank you very much for your answer

i already install pyhon and google-api-python-client lib

then i execute` python script/spider.py -c config/prod.cfg`
![capture2](https://cloud.githubusercontent.com/assets/15624898/15452497/6ba42cec-201a-11e6-9fef-b9ca0d061dd6.JPG)

**Comment by niqdev** [comment]
Which Python version are you currently using? From [docs](https://docs.python.org/3.0/whatsnew/3.0.html) `print` has a different signature in version 3.x

**Comment by fariz0020** [comment]
I currently using python version 3.5.1

**Comment by niqdev** [comment]
So have you tried to install v2.x? Let me know if it works. Thanks

**Comment by fariz0020** [comment]
I do what you said mr.niqdev

but there still error,

![capture3](https://cloud.githubusercontent.com/assets/15624898/15456164/51206408-2092-11e6-9c3d-75405e0086a4.JPG)

**Comment by niqdev** [comment]
Looks better!
I think you are missing some dependencies... [python-magic](https://github.com/ahupp/python-magic#installation)
Try with `pip install python-magic`, do the same with other libs if you have other `ImportError`

**Comment by niqdev** [comment]
@fariz0020 I've updated the README, I think should be more clear now.
Can you tell me if it works, please? So I can close the issue.
Thanks

**Comment by fariz0020** [comment]
After i install python-magic, i still met with error here, mr.niqdev

![capture4](https://cloud.githubusercontent.com/assets/15624898/15575825/0adb4b30-237f-11e6-9c41-df90d706ba67.JPG)

**Comment by niqdev** [comment]
I'm sorry that you are having so many errors, but [googling](https://www.google.it/search?q=windows+error+193+is+not+a+valid+win32+application) it seems that python or some libs you have installed are 64bit while are expected to be 32bit or viceversa. Have a look at that!

**Comment by fariz0020** [comment]
Its okay, may this issue can help the others,
Mr. niqdev, there something weird occured,
![capture5-1](https://cloud.githubusercontent.com/assets/15624898/15630209/2ba0ce30-255a-11e6-9679-c27a601e2167.JPG)
![capture5-2](https://cloud.githubusercontent.com/assets/15624898/15630216/38e733cc-255a-11e6-90cc-3a8083659ca8.JPG)

**Comment by niqdev** [comment]
Hi, the error about `html5lib` is already fixed, just pull the last version from the repo!

**Comment by fariz0020** [comment]
Thank you very much mr.niqdev.
It's already worked, 
I will close this issue,

but there a little trouble here when i execute this command
`
python script/spider.py --config config/prod.cfg --all --extras --upload drive
`
it cant upload the files after download completed.

**Comment by niqdev** [comment]
I'm happy about that, finally we did it!
Which kind of error do you have? Did you follow all the instructions in the README? If you need help please open another issue regarding the problem.
Thanks
