### ISSUE TITLE
Subscribe to download ebook 

### ISSUE THREAD

**Issue by Mehran** [niqdev/packtpub-crawler#22]
i have subscribe account on packtpub i just can read all books online , now can i download books with this way ?

**Comment by niqdev** [comment]
Hi,
sorry I don't know if I understood correctly the question. Would you like to download books that you have  already in your account?
The idea of this project is that once you have configured everything you forget about it and every day you will receive an email with the link of the ebook uploaded on google drive.

**Comment by Mehran** [comment]
Thanks . on my account i just can read all ebooks Online  , but  i cant download .

**Comment by niqdev** [comment]
So I've opened another [issue](https://github.com/niqdev/packtpub-crawler/issues/23) to backup all old subscribed ebook at once. But at the moment is not supported.
I will close this issue, but if you have any other idea or you need help feel free to re-open it.
