### ISSUE TITLE
upload issue

### ISSUE THREAD

**Issue by Mehran** [niqdev/packtpub-crawler#24]
i use ubuntu 16.04 server and no any gui , how can i do with this ?

`Only the first time you will be prompted to login in a browser which has javascript enabled`

i dont have any browser on my server .

**Comment by niqdev** [comment]
I know that is a bit annoying but unfortunately that's google api, unless they change it lately, so I suggest to run it the first time on your local machine and then upload the configurations on the server with scp for example.
