### ISSUE TITLE
libmagic

### ISSUE THREAD

**Issue by frederikkunze** [niqdev/packtpub-crawler#33]
I get following error on windows.
I did `pip install -r requirements.txt` before but it seems to not resolve all requirements.
  File "C:\Python27\lib\site-packages\magic.py", line 171, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by juzim** [comment]
What OS do you use? On Windows, you can give [this]( http://stackoverflow.com/questions/24816887/python-magic-unable-to-find-libmagic) a try since there seem to be lots of cygwin related issues with libmagic.

**Comment by niqdev** [comment]
Hi, I google it a bit and as @juzim said, seems to be a problem related to windows.
If you don't have any constraint, I would suggest to use the docker image, just follow the readme.
Honestly I can't do much on this, feel free to reopen the issue if you have any other doubt or you find a solution that can help other people

**Comment by frederikkunze** [comment]
I think I found a solution https://github.com/ahupp/python-magic#dependencies but where do I have to pass Magic(magic_file=...)?
