### ISSUE TITLE
Check if there is a free book today

### ISSUE THREAD

**Issue by juzim** [niqdev/packtpub-crawler#34]
Today packtpub has a different free offer and no ebook. 

We should check if the correct heading/button exists on https://www.packtpub.com/packt/offers/free-learning to prevent confusing error messages.
I'm not sure if we should still send out error notifications or just log and skip it.

**Comment by niqdev** [comment]
The error is this?

```
[-] <type 'exceptions.AttributeError'> 'NoneType' object has no attribute 'select' | spider.py@90
Traceback (most recent call last):
  File "script/spider.py", line 90, in main
    run(packpub, args, config)
  File "script/spider.py", line 19, in run
    packpub.run()
  File "XXX/packtpub-crawler/script/packtpub.py", line 115, in run
    self.__POST_login()
  File "XXX/packtpub-crawler/script/packtpub.py", line 75, in __POST_login
    title = div_target.select('div.dotd-title > h2')[0].text.strip()
AttributeError: 'NoneType' object has no attribute 'select'
```

**Comment by juzim** [comment]
There is a toaster message saying that there won't be any more free ebooks in 2016.

**Comment by niqdev** [comment]
Hopefully..without any breaking changes!

**Comment by juzim** [comment]
New free books are out, scraping of daily offers and the weekly newsletter is still working! 	
\( ﾟヮﾟ)/

**Comment by niqdev** [comment]
Yep! Latest version is `2.2.2`
