### ISSUE TITLE
Book thumbnail would be useful

### ISSUE THREAD

**Issue by lucymhdavies** [niqdev/packtpub-crawler#44]
I have this setup with IFTTT to send a Slack notification.

It would be nice to include the book's thumbnail as part of the notification.

**Comment by juzim** [comment]
I don't think we should hotlink the images from packtpub and the local images would't be accessible without further configuration (server, ports etc).

The only solution I see is to parse the images separately and upload them to a shared folder somewhere. I'll look into it.

**Comment by juzim** [comment]
Nevermind. Since we are already sending out the image URL, we can also pass it to ifttt I guess.
Added in https://github.com/niqdev/packtpub-crawler/pull/45, image URL is passed as {{Value3}}.

**Comment by niqdev** [comment]
@juzim Thanks! I will update the version also to `2.2.3`
