### ISSUE TITLE
Deprecated NoBookException references need removed

### ISSUE THREAD

**Issue by jsears** [niqdev/packtpub-crawler#51]
From packtpub.py and spider.py
Else you get:
Traceback (most recent call last):
  File "script/spider.py", line 8, in <module>
    from packtpub import Packtpub
  File "/home/pclarity/packt-crawler2/script/packtpub.py", line 6, in <module>
    from noBookException import NoBookException
ImportError: No module named noBookException

**Comment by juzim** [comment]
The file was deleted accidentally, no idea why I didn't caught it before.

pclarity <notifications@github.com> schrieb am Do., 2. Feb. 2017, 14:37:

**Comment by juzim** [comment]
Fixed in https://github.com/niqdev/packtpub-crawler/pull/52

**Comment by niqdev** [comment]
Thanks @juzim
