### ISSUE TITLE
video

### ISSUE THREAD

**Issue by jaan143** [niqdev/packtpub-crawler#53]
hi 
i want to download video course from packtpub 
can you plz add this option also ?
thanks

**Comment by juzim** [comment]
Hi!

Can you point me to a free video on packtpub? Just to be sure: this script
only claims freely available content in promotions, it will not give you
access to normal books or videos for free.

jaan143 <notifications@github.com> schrieb am Do., 16. Feb. 2017, 14:42:

**Comment by jaan143** [comment]
packt publisher allow video courses on their mapt subscription
they allow to watch online only cant download 
so you can make downloading script in python that will download course after giving login

**Comment by lucymhdavies** [comment]
1. sounds out of scope of this tool
2. sounds against Packt ToS. if they wanted you to be able to download the videos, they would have made it easier to do so

**Comment by niqdev** [comment]
This maybe help you https://github.com/soimort/you-get

**Comment by niqdev** [comment]
If it works, can you please share a request example? Thanks

**Comment by juzim** [comment]
I haven't bought any videos but this looks like video downloads are possible: https://www.packtpub.com/books/content/support-video

> How to download video packages for offline viewing
Login to your account at Packtpub.com.
Click on "My Account" and then click on the "My Videos" tab to access your videos.
Click on the "Download Now" link to start your video download.

I also think this has nothing to do with this script and can easily be solved by picking the file URL from the DOM or using a tool like you-get. If the file URL is not in the DOM but loaded dynamically, there is no way for us to download the file anyways.

Here are a few suggestion on how to find the video file URL: https://www.quora.com/How-can-I-scrape-videos-from-websites

**Comment by jaan143** [comment]
hi
i checked supported site lists of this app
https://github.com/soimort/you-get

they dont have packtpub in their list

**Comment by juzim** [comment]
So? I really don't think we can help you here. Why don't you ask packtpub
for help?

jaan143 <notifications@github.com> schrieb am Fr., 17. Feb. 2017, 15:09:

**Comment by niqdev** [comment]
@jaan143 to be able to use [you-get](https://you-get.org/) I'm expecting that you look manually for the video url in the DOM and if supported somehow by the library you may need to add some extra header to handle the authentication

**Comment by niqdev** [comment]
By the way, I'm not saying that what I suggested is the right tool for your needs, but you should have a look at something similar or fork that repo

**Comment by niqdev** [comment]
The downloading of video is out of scope of this project.
