### ISSUE TITLE
invalid syntax error

### ISSUE THREAD

**Issue by lcorsini** [niqdev/packtpub-crawler#58]
I've placed my credentials in prod.cfg
when I run python script/spider.py --config config/prod.cfg --claimOnly I get this error:

Traceback (most recent call last):
  File "script/spider.py", line 7, in <module>
    from utils import ip_address, config_file
  File "/home/csllc4/packtpub-crawler/script/utils.py", line 16
    print '[-] GET {0} | {1}'.format(response.status_code, response.url)
                            ^
SyntaxError: invalid syntax

**Comment by lcorsini** [comment]
uhmm that error was from my natted virtual machine.
Tried from a VPS with public address and it's working

**Comment by niqdev** [comment]
Hi, sorry for the late response, if is working, can I close the issue or do you have any other problem?
Thanks

**Comment by lcorsini** [comment]
you can close, I cannot reproduce the error on any other machine than this (an archlinux VM) so probably is some problem here
