### ISSUE TITLE
Heroku Scheduler instructions

### ISSUE THREAD

**Issue by brechtm** [niqdev/packtpub-crawler#69]
It makes sense to use the Heroku Scheduler add-on as it requires much less dyno hours since it doesn't run continuously like the clock. The README is not clear on how to use the add-on however. Some questions:

* Is it enough to just add the Scheduler add-on to the Heroku app?
* The [Heroku docs](https://devcenter.heroku.com/articles/scheduler) mention that the Scheduler occasionally can miss the execution of scheduled jobs. Can this result in missing out on free books, or is this risk minimized by running the job every hour instead of only once a day?
* If the job is run every hour (or every 10 minutes), will I receive the notification email each time or does packtpub-crawler somehow detect that the free book of the day was already claimed?

**Comment by niqdev** [comment]
Hi,
actually I suggest you to just follow the [commands](https://github.com/niqdev/packtpub-crawler#heroku), you don't need to setup any add-on manually (as far as I remember).

The command `heroku ps:scale clock=1` will start the scheduler for you and internally what runs is [scheduler.py](https://github.com/niqdev/packtpub-crawler/blob/master/script/scheduler.py)

I think the missing execution is referred to high frequency scheduler, I never encounter any issue on this.

If you want change the scheduler time you need to change the file that I linked above manually, and yes, every time is run it will claim again the book, upload a new copy and send a new notification.

I hope I've answered to your question.
Thanks

**Comment by brechtm** [comment]
Following the commands sets up a clock app which runs 24/7 and thus leaves the free dyno unavailable for other things. It is not using the Heroku Scheduler by default.

I have now set up the Heroku Scheduler add-on [as described here](https://stackoverflow.com/a/38000618/438249) and set it to run `python script/spider.py` (+ options) once daily. This used the free dyno only a couple of minutes each day. The only drawback is that the scheduler occasionally (but rarely) fails to trigger, so I could miss out on a book.

**Comment by niqdev** [comment]
Yep, I got it now, thanks. If you want feel free to update the readme with your configuration then.
