### ISSUE TITLE
recaptcha cause daily free ebook acquisition failure.

### ISSUE THREAD

**Issue by jerrywang1974** [niqdev/packtpub-crawler#72]
Hi ,
recently packtpub change a little bit for getting daily free ebook and need to pass reCAPTCHA to acquire the free ebook, and it cause the daily job failure, you need manually pass reCAPTCHA and get ebook in your account and using download all ebook(-dall) to get ebook, does it possible to improvement on this? Thanks!

**Comment by niqdev** [comment]
Hi, duplicate issue #70 thanks
