### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by vpontin** [niqdev/packtpub-crawler#73]
Hi!
I'm trying to use this crawler but i'm having only errors.

I use Python 2 and 3 (using pylauncher) and even after running the requeriments txt file:
`py -2 -m pip install -r requirements.txt`

I've got this error when running the script (`py -2 script/spider.py --config config/prod.cfg -t pdf --extras`):

https://gist.github.com/vpontin/cfa2e42556624a3a5b9252351bf02f72

Using Win10 Creators update x64

**Comment by niqdev** [comment]
hi, this might help #33 , keep in mind that the reCaptha is blocking the script at the moment

**Comment by NikolasMiz** [comment]
reCaptha has been removed
