### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by icepaule** [niqdev/packtpub-crawler#76]
Hello,

having the below issue and hoping that you could give me a little help.

Cheers
Marcus
[*] 2017-06-20 15:05 - fetching today's eBooks
[*] configuration file: /opt/packtpub-crawler/config/prod.cfg
[*] getting daily free eBook
[*] fetching url... 200 | https://www.packtpub.com/packt/offers/free-learning
[*] fetching url... 200 | https://www.packtpub.com/packt/offers/free-learning
[-] <type 'exceptions.IndexError'> list index out of range | spider.py@97
Traceback (most recent call last):
  File "/opt/packtpub-crawler/script/spider.py", line 97, in main
    packtpub.runDaily()
  File "/opt/packtpub-crawler/script/packtpub.py", line 161, in runDaily
    self.__parseDailyBookInfo(soup)
  File "/opt/packtpub-crawler/script/packtpub.py", line 93, in __parseDailyBookInfo
    self.info['url_claim'] = self.__url_base + div_target.select('a.twelve-days-claim')[0]['href']
IndexError: **list index out of range**
[*] no free eBook from newsletter right now
[*] done

pip install -r requirements succeeded fine, using Ubuntu 16.04.  :-)

**Comment by niqdev** [comment]
@icepaule thanks, please look at #70
