### ISSUE TITLE
cron suggestion

### ISSUE THREAD

**Issue by windhamwong** [niqdev/packtpub-crawler#8]
I don't think adding cron feature onto the script is a good idea.
However, if you can have a guide for adding a line on crontab to run it every day in README.MD, it would be better so it won't make the script heavy loaded.
What I have used in crontab is:
`0 9 * * * python /home/<username>/packtpub_crawler/script/spider.py --config /home/<username>/packtpub_crawler/config/prod.cfg --all --extras --upload drive`

**Comment by niqdev** [comment]
Great! I will add this option also in the README.md for sure.
I'm working now on another branch, I don't have a dedicated server and I don't wont run this locally, so I'm configuring a [scheduler on Heroku](https://github.com/niqdev/packtpub-crawler/issues/5), it's free if you don't exceed the free dynos

**Comment by windhamwong** [comment]
I never use it before, I will have a look on it.

**Comment by niqdev** [comment]
@windhamwong I've added support for [heroku](https://github.com/niqdev/packtpub-crawler#heroku-setup). Please let me know if is clear and helpful. I will add soon in the Readme the `cron` example or if you want make a pull request with a step-by-step tested config, you are welcome!

**Comment by niqdev** [comment]
Sorry I'm very busy in this period, I will update the readme soon. Did you try the heroku cron?

**Comment by niqdev** [comment]
I will reopen this issue just as reminder!

**Comment by windhamwong** [comment]
Oh I thought you have finished deployment. I am not so interested with the heroku sry
