### ISSUE TITLE
error on script.py line 97

### ISSUE THREAD

**Issue by doraeball22** [niqdev/packtpub-crawler#83]
Download FREE eBook every day from www.packtpub.com
@see github.com/niqdev/packtpub-crawler

[*] 2017-11-26 01:56 - fetching today's eBooks
[*] configuration file: /packtpub-crawler/config/prod.cfg
[*] getting daily free eBook
[*] fetching url... 200 | https://www.packtpub.com/packt/offers/free-learning
[*] fetching url... 200 | https://www.packtpub.com//packt/offers/free-learning?login=1
[-] <type 'exceptions.IndexError'> list index out of range | spider.py@97
Traceback (most recent call last):
  File "script/spider.py", line 97, in main
    packtpub.runDaily()
  File "/packtpub-crawler/script/packtpub.py", line 161, in runDaily
    self.__parseDailyBookInfo(soup)
  File "/packtpub-crawler/script/packtpub.py", line 93, in __parseDailyBookInfo
    self.info['url_claim'] = self.__url_base + div_target.select('a.twelve-days-claim')[0]['href']
IndexError: list index out of range
[*] no free eBook from newsletter right now
[*] done

**Comment by niqdev** [comment]
Duplicate issue, please refer to #70
