### ISSUE TITLE
SCP upload feature or other upload method

### ISSUE THREAD

**Issue by windhamwong** [niqdev/packtpub-crawler#9]
The script is cron running for 17 days now. The Un!ty books have large zip files and they are filling up my drive. Looks like we do need alternative method to do the upload. SCP would be great I think? Or should we make a feature of running script every time it finished download?

**Comment by niqdev** [comment]
Hi,
if you need this feature I would suggest to add in [spider.py](https://github.com/niqdev/packtpub-crawler/blob/master/script/spider.py) and [upload.py](https://github.com/niqdev/packtpub-crawler/blob/master/script/upload.py) another service like `SERVICE_SCP`

```
parser.add_argument('--upload', choices=[SERVICE_DRIVE, SERVICE_DROPBOX, SERVICE_SCP])
```

and than I think we could use
* [Pexpect](https://pexpect.readthedocs.io/en/stable/index.html) or his brother pxssh
* [paramiko](https://github.com/paramiko/paramiko) (never used it)
* [scpclient](https://pypi.python.org/pypi/scpclient) (never used it)

What do you think?

**Comment by windhamwong** [comment]
Not sure which library is the best but I think i will try on them later. I will try to commit it before my drive is using up (within 2weeks i believe).

**Comment by niqdev** [comment]
Thanks @kuchy I've update also the readme
